name: Using Workflow with Basic definition

on:
  push:
    branches: [ "main1" ]
  pull_request:
    branches: [ "main1" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Welcome to learn Git Action Basic
        
      - name: Run a multi-line script
        run: |
          echo Hi
          echo I am running with ${GITHUB_REF##*/}
        
