name: Experiment environemt GIT actions
on: workflow_dispatch

jobs:
  job1:
    runs-on : ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
    steps:
      - name: Display Environment
        run: echo ${{ env.ENVIRONMENT_NAME }}
        
