name: Experiment environemt GIT actions
on: workflow_dispatch

jobs:
  env:
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
  setup: 
    runs-on : ubuntu-latest
    steps:
       - name: Display Environment
         run: echo $ENVIRONMENT_NAME
        