name: Experiment environemt GIT actions
on: workflow_dispatch

jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Display Environment
        run: echo ${{ secrets.ENVIRONMENT_NAME }}
        
