name: Build action for learing GIT actions
on: workflow_dispatch

jobs:

  setup: 
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2   
        with:
          gradle-version: 6.9
      - name: Build Gradle
        run: gradle build
      - name: Bump version and push tag ${{ env.ENABLE_RELEASE }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: myrepo-actions/publish-docker@main
        with:
          docker_user_name: ${{secrets.DOCKERHUB_USERNAME}}
          docker_token: ${{secrets.DOCKERHUB_TOKEN}}
          docker_file: Dockerfile
          docker_tag_name: sisuseta/learning-githubaction:${{ steps.tag_version.outputs.new_tag }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}    
        
