name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      resultString:
        description: "Output String"
        value: ${{ jobs.say_hi.outputs.output1 }}
    inputs:
      branchName:
        required: true
        type: string

jobs:
  say_hi:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: echo "result=hi ${{inputs.branchName}}" >> $GITHUB_OUTPUT
