name: Using the reusable workflows
on: workflow_dispatch
jobs:
 sayHi:
    uses: ./.github/workflows/sample_reusableworkflow.yml
    with:
     branchName: "main"
    secrets: inherit
 showHi:
    runs-on : ubuntu-latest
    needs: sayHi
    steps:
      - name: Display output from reusable environment
        run: echo ${{ needs.sayHi.outputs.resultString }}
