name: Using the reusable workflows
on: workflow_dispatch
jobs:
 sayHi:
    uses: experiment-repo/git-actions-sample/.github/workflows/sample_reusableworkflow.yml@main
    with:
     branchName: ${GITHUB_REF##*/}
 showHi:
    runs-on : ubuntu-latest
    needs: sayHi
    steps:
      - name: Display output from reusable environment
        run: echo ${{ needs.sayHi.outputs.resultString }}
