name: Usage of environment and secret

on:
  workflow_dispatch: 

jobs:
  use_develop:
    # This job only runs for pull request
    name: Use develop environment
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - name: Show secret
        run: | 
          echo ${{ secrets.ENVIRONMENT_NAME}}
          echo ${{ secrets.ENVIRONMENT_NAME}}| sed 's/./& /g'



  use_production:
    # This job only runs for pull request
    name: Use production environment
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Show secret
        run: | 
          echo ${{ secrets.ENVIRONMENT_NAME}}
          echo ${{ secrets.ENVIRONMENT_NAME}}| sed 's/./& /g'
