name: Using Custom Actions 

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Composite actions
        uses: experiment-repo/myorg-actions/greet-composite@main
        with:
          branch_name: main
          
