name: Using Workflow with Basic definition

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Gradle and Publish
        run: gradle build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: ./build
        
